### PR TITLE
Fixed permissions on gaia created folders and pipelines.

### LINKED ISSUE #185: Set pipeline binary OS permissions accordingly
Pipelines build by Gaia are automatically copied to the pipelines folder with `0766` permissions. For example: https://github.com/gaia-pipeline/gaia/blob/master/workers/pipeline/build_cpp.go#L92

In my opinion, this is currently not "least privilege" since only the current user needs access rights and not the whole group + everyone else.

The proposed solution is to change this to `0700`. This allows the current user to execute, read and write (e.g. delete) the pipeline.

### PR DESCRIPTION
**Pull request by Skarlso**
Closes #185

### CODE REVIEW

File: handlers/pipeline_test.go [hunk 1]
```diff
@@ -129,7 +129,7 @@ Xbs5AQIEIzWnmQIFAOEml+E=
 		})
 		hostConfig := "github.comom,1.2.3.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
 		knownHostsLocation := filepath.Join(dataDir, ".known_hosts")
-		ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), 0766)
+		ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), gaia.ExecutablePermission)
```
Comment (golangcibot) [inline handlers/pipeline_test.go]: Error return value of `ioutil.WriteFile` is not checked (from `errcheck`)

File: workers/pipeline/git_test.go [hunk 2]
```diff
@@ -118,7 +118,7 @@ Xbs5AQIEIzWnmQIFAOEml+E=
 	}
 	hostConfig := "notgithub.comom,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
 	knownHostsLocation := filepath.Join(tmp, ".known_hosts")
-	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), 0766)
+	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), gaia.ExecutablePermission)
```
Comment (golangcibot) [inline workers/pipeline/git_test.go]: Error return value of `ioutil.WriteFile` is not checked (from `errcheck`)

File: workers/pipeline/git_test.go [hunk 3]
```diff
@@ -159,7 +159,7 @@ Xbs5AQIEIzWnmQIFAOEml+E=
 	}
 	hostConfig := "github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
 	knownHostsLocation := filepath.Join(tmp, ".known_hosts")
-	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), 0766)
+	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), gaia.ExecutablePermission)
```
Comment (golangcibot) [inline workers/pipeline/git_test.go]: Error return value of `ioutil.WriteFile` is not checked (from `errcheck`)

File: go.mod [hunk 4]
```diff
@@ -11,6 +11,7 @@ require (
 	github.com/emirpasic/gods v1.9.0 // indirect
 	github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568 // indirect
 	github.com/gaia-pipeline/flag v1.7.4-pre
+	github.com/gaia-pipeline/gosdk v0.0.0-20180909192508-cc9f89055777
```
Comment (michelvocks) [inline go.mod]: Is this new dependency necessary?

Comment (Skarlso) [reply go.mod]: Interesting. No idea how it came here. :D

Comment (Skarlso) [reply go.mod]: Apparently it wasn't. `go mod tidy` removed it. I think my IDE must have added it?

File: workers/pipeline/git_test.go [hunk 5]
```diff
@@ -174,7 +182,7 @@ Xbs5AQIEIzWnmQIFAOEml+E=
 	GlobalActivePipelines = NewActivePipelines()
 	GlobalActivePipelines.Append(*p)
 	hostConfig = "invalid.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), 0766)
+	ioutil.WriteFile(knownHostsLocation, []byte(hostConfig), gaia.ExecutablePermission)
```
Comment (golangcibot) [inline workers/pipeline/git_test.go]: Error return value of `ioutil.WriteFile` is not checked (from `errcheck`)
